/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * QueryTester2.java
 *
 * Created on 19.10.2010, 22:18:45
 */

package cz.uhk.ppro.jpa.exercise;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;


/**
 *
 * @author Kriz
 */
public class QueryTester extends javax.swing.JFrame {
	private static final long serialVersionUID = -1708370526792454798L;
	
	private String unitName = "jpa-cviceni";
	private EntityManagerFactory emf = Persistence.createEntityManagerFactory(unitName);
	private EntityManager em = emf.createEntityManager();

    /** Creates new form QueryTester2 */
    public QueryTester() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("JPQL dotaz:");

        jLabel2.setText("Vysledek:");

        jScrollPane1.setViewportView(jTextPane1);

        jButton1.setText("Spustit");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jScrollPane2.setViewportView(jTextPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(344, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String output = "";
            @SuppressWarnings("unchecked")
			List<Object> result = em.createQuery(jTextPane1.getText()).getResultList();
            if (result.size() > 0) {
                int count = 0;
                for (Object o : result) {
                    output = output +  (++count) + " ";
                    output = output + getResult(o);
                }
            } else {
                output = output + "0 results returned\n";
            }
            jTextPane2.setText(output);
	} catch (Exception e) {
            jTextPane2.setText("Chyba - viz konzole");
            e.printStackTrace();
	}
    }//GEN-LAST:event_jButton1ActionPerformed

    private static String getResult(Object result) {
                String output = "";
		if (result == null) {
			output = "NULL";
		} else if (result instanceof Object[]) {
			Object[] row = (Object[]) result;
			output = output + "[";
            for (Object aRow : row) {
                output = output + getResult(aRow);
            }
			output = output + "]";
		} else if (result instanceof Long ||
				result instanceof Double ||
				result instanceof String) {
			output = output + result.getClass().getName() + ": " + result;
		} else {
			output = output + ReflectionToStringBuilder.toString(result, ToStringStyle.SHORT_PREFIX_STYLE);
		}
		output = output + "\n";
                return output;
	}

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new QueryTester().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    // End of variables declaration//GEN-END:variables

}
